"""rename department

Revision ID: 2f5e01f9e7b0
Revises: 9b3421e51dd2
Create Date: 2024-05-26 21:10:19.613200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5e01f9e7b0'
down_revision = '9b3421e51dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
